export const mockFeedbackData = [
  {
    question: "Tell me about yourself?",
    answerRelevance: "Your answer was a bit confusing and lacked clear structure. While you mentioned a project where you led a team, the explanation was unclear about the challenge you faced and how you navigated it. In a response to this question, you should provide a clear narrative by explaining the context (situation), the problem you encountered, the actions you took to solve it, and the results you achieved. This will allow the interviewer to better understand your problem-solving and leadership abilities.",
    grammar: "Your answer could benefit from improved clarity by paying closer attention to the correct usage of articles and prepositions. For example, instead of saying 'I leave my team for the requirements,' the correct phrasing would be 'I led my team to meet the requirements.' Additionally, be mindful of verb tenses—use past tense when describing actions you have already completed, and present tense when referring to your current role or responsibilities.",
    eyeContact: "Your eye contact during the interview was inconsistent. Maintaining steady eye contact with the interviewer is important as it conveys confidence and helps build rapport. Aim to keep eye contact for about 50-60% of your answer, especially when making key points, but don’t stare aggressively. If you need to look away to gather your thoughts, do so briefly and return to eye contact promptly.",
    paceOfSpeech: "Your pace of speech was inconsistent. There were moments when you spoke too quickly, making it difficult for the interviewer to follow your thoughts. When you speak too quickly, you might appear anxious, and the interviewer may miss important details. At other times, your speech was too slow, which can come across as hesitation or uncertainty. Try to find a balance—speak clearly and at a moderate pace so the interviewer can absorb your points without feeling rushed or bored.",
    fillerWords: "You frequently used filler words such as 'um,' 'uh,' 'like,' and 'you know.' These fillers are distracting and can make you sound less confident. To avoid fillers, practice pausing for a moment before speaking. Pauses give you time to collect your thoughts and make your response sound more confident and polished. Try recording yourself to become aware of the fillers and practice reducing them.",
    tips: "When answering behavioral questions like this, it's helpful to structure your response using the STAR method: Situation, Task, Action, and Result. This ensures your answer is structured and covers all relevant aspects. Additionally, focus on eliminating filler words and maintaining steady eye contact. Both of these practices will help improve your overall delivery and make your answer more impactful.",
  },
  {
    question: "Why do you want to work for this company?",
    answerRelevance: "Your answer was mostly relevant, but it could have been more specific. You mentioned the company's reputation, which is a good starting point, but you didn't elaborate on why you believe this company is a good fit for your skills, values, and career goals. It's important to align your answer with what the company offers and how it matches your interests. Tailor your response to highlight the specific aspects of the company that excite you, such as its culture, mission, or innovation in the industry.",
    grammar: "Your grammar was mostly correct, but there was a minor issue with verb tense. Instead of saying 'I am passionate about working for this company because it has a good reputation,' it would be clearer to say 'I am passionate about working for this company because it has built a strong reputation.' Pay attention to verb tense consistency throughout your response.",
    eyeContact: "Your eye contact was generally good, but there were moments when it was broken or inconsistent. Maintaining strong, consistent eye contact throughout your response is crucial in conveying confidence. Avoid looking down or away for long periods, as it can suggest uncertainty or disinterest. Instead, focus on keeping eye contact while speaking and nodding occasionally to show engagement.",
    paceOfSpeech: "The pace of your speech was well-paced throughout the answer. You spoke clearly, and the flow of your answer was easy to follow. Keep up this steady pace to ensure the interviewer doesn't feel rushed or bored. It also gives you enough time to consider your responses thoughtfully and deliver them more confidently.",
    fillerWords: "You used a few filler words such as 'um,' 'like,' and 'you know.' While they were not excessive, it would still be helpful to reduce their use. Try to practice delivering your answers smoothly without relying on these words by pausing to gather your thoughts instead. This will help you appear more confident and make your answers sound more professional.",
    tips: "When answering this question, it's important to show that you've researched the company. Focus on aligning your professional goals with the company's mission or values, and highlight how your skills can contribute to the company's success. Use specific examples to demonstrate that you’ve done your homework and are genuinely excited about the opportunity.",
  },
  {
    question: "What are your strengths and weaknesses?",
    answerRelevance: "Your response was on point regarding your strengths, but it could have gone into more detail about your weaknesses. When discussing weaknesses, it's essential to focus on areas where you're actively working to improve. Avoid listing generic traits like 'I'm a perfectionist.' Instead, consider focusing on a real challenge you've faced and the steps you're taking to overcome it. This shows self-awareness and a willingness to grow.",
    grammar: "There were some minor grammatical issues in your answer, but they did not significantly hinder your message. For example, 'I don't good with criticism' should be 'I don't handle criticism well.' It’s also important to ensure your sentence structure is clear and concise. Consider practicing more complex sentences to improve the flow of your answers.",
    eyeContact: "Your eye contact was generally good, but it could be steadier throughout your answer. When talking about your strengths and weaknesses, it’s important to make eye contact with the interviewer to convey confidence and transparency. Steady eye contact helps build trust and shows that you’re comfortable discussing both your strengths and areas for improvement.",
    paceOfSpeech: "The pace of your speech was generally good, but you seemed a little hesitant at times. Confidence in this type of question is key. Practice answering similar questions to ensure you can articulate your strengths and weaknesses more fluidly. Taking a deep breath before answering will also help calm any nerves and improve your delivery.",
    fillerWords: "You used a few filler words like 'uh' and 'you know.' While these were not overly distracting, it would be helpful to reduce them for a smoother delivery. Pausing for a moment before speaking can allow you to gather your thoughts and deliver a more polished and confident response.",
    tips: "When answering this question, it's crucial to focus on one strength and one weakness that are both relevant to the job you're applying for. Show how you're actively working on improving your weakness, as this demonstrates self-awareness and a commitment to growth. Use concrete examples to highlight how you've worked to overcome your weaknesses in the past.",
  },
  {
    question: "Describe a time when you faced a challenge at work and how you overcame it.",
    answerRelevance: "Your answer was relevant but lacked depth in some areas. It's important to provide more details when explaining challenges. Describe the specific situation, the task you were faced with, the actions you took, and the results that followed. This will help the interviewer understand how you approach problem-solving and how you overcome obstacles in your work.",
    grammar: "Your grammar was mostly accurate, but the phrasing could be improved for clarity. For example, 'I was in a situation where we needed to fix a problem' could be rephrased as 'I encountered a situation where we had to solve a problem.' It's also important to keep your sentences concise and to the point, avoiding unnecessary filler language.",
    eyeContact: "Your eye contact was inconsistent during this answer. Focus on maintaining steady eye contact with the interviewer to convey engagement and confidence. Eye contact is particularly important when discussing challenges, as it shows that you're taking ownership of the situation and are confident in your ability to overcome difficulties.",
    paceOfSpeech: "The pace of your speech was good, but you occasionally sounded rushed when explaining the steps you took to resolve the challenge. Take your time when describing your actions to ensure your answer is clear and well-structured. Don’t be afraid to pause to gather your thoughts—it will make your answer sound more composed and confident.",
    fillerWords: "You used a number of filler words in this answer, such as 'um' and 'you know.' These detract from your credibility and can make your answer sound less polished. Try to minimize filler words by pausing briefly before speaking. This will help you sound more thoughtful and in control of your response.",
    tips: "When answering behavioral questions, the STAR method is extremely helpful. Be sure to describe the Situation, the Task at hand, the Actions you took, and the Results of your efforts. This method ensures your answer is structured and covers all relevant details. Avoid rushing through the answer, and instead focus on delivering a well-thought-out response that highlights your problem-solving skills.",
  },
  {
    question: "Where do you see yourself in five years?",
    answerRelevance: "Your response was a bit vague and lacked specificity. Instead of saying something broad like 'I want to be successful,' it’s better to articulate concrete goals that align with both your personal aspirations and the company’s growth. Discuss how you envision your career evolving and how this role can help you achieve those goals. This shows the interviewer that you're motivated and have a clear vision for your career path.",
    grammar: "Your grammar was fine, but the sentence structure could be clearer. For example, 'I see myself being successful and working for a company like this' could be reworded to 'In five years, I see myself in a leadership position at a company like this, contributing to its success.' Clarity is key when discussing your future aspirations.",
    eyeContact: "Your eye contact was good, but there were moments when it seemed like you were looking around the room. Try to keep your focus on the interviewer to maintain a sense of connection and confidence. When discussing your future goals, it’s important to be assertive and maintain direct eye contact, which helps convey your enthusiasm and commitment to the role.",
    paceOfSpeech: "The pace of your speech was steady, but you seemed uncertain at times when discussing your long-term goals. Practice talking about your future aspirations with confidence. Be sure to take a deep breath before answering, and focus on delivering a clear, concise response that reflects your excitement and commitment to your career.",
    fillerWords: "You used a few filler words, which made your answer sound less polished. While it's normal to take a moment to gather your thoughts, try to avoid filling the space with 'um' or 'like.' By practicing your response ahead of time, you can answer more confidently without relying on these fillers.",
    tips: "When discussing your future, it's important to show both ambition and alignment with the company’s goals. Be specific about how you envision growing within the company, and emphasize how your long-term aspirations are aligned with the company’s mission. Employers want to know that you're thinking about your future, and that it’s aligned with theirs.",
  }
];


